// Includes all /algorithm headers.
#pragma once

#include "algorithm/algorithm.hpp"
#include "algorithm/bigint.hpp"
#include "algorithm/bit-manipulators.hpp"
#include "algorithm/dijkstra.hpp"
#include "algorithm/dsu.hpp"
#include "algorithm/edmonds-karp.hpp"
#include "algorithm/fenwick.hpp"
#include "algorithm/fibonacci.hpp"
#include "algorithm/floyd-warshall.hpp"
#include "algorithm/geometry.hpp"
#include "algorithm/huffman.hpp"
#include "algorithm/kmp.hpp"
#include "algorithm/lru.hpp"
#include "algorithm/math.hpp"
#include "algorithm/miller-rabin.hpp"
#include "algorithm/modulus-field.hpp"
#include "algorithm/segment-tree-lazy.hpp"
#include "algorithm/segment-tree.hpp"
#include "algorithm/sieve.hpp"
#include "algorithm/spfa.hpp"
