// Includes all /algorithm headers.
#pragma once

#include "algorithm/algorithm.hpp"
#include "algorithm/big_integer.hpp"
#include "algorithm/bit_manipulators.hpp"
#include "algorithm/dijkstra.hpp"
#include "algorithm/dsu.hpp"
#include "algorithm/edmonds_karp.hpp"
#include "algorithm/fenwick.hpp"
#include "algorithm/fibonacci.hpp"
#include "algorithm/floyd_warshall.hpp"
#include "algorithm/gcd_lcm.hpp"
#include "algorithm/geometry.hpp"
#include "algorithm/heirholzer.hpp"
#include "algorithm/huffman.hpp"
#include "algorithm/kmp.hpp"
#include "algorithm/kosaraju.hpp"
#include "algorithm/lru.hpp"
#include "algorithm/miller_rabin.hpp"
#include "algorithm/modulus_field.hpp"
#include "algorithm/partitions.hpp"
#include "algorithm/prim.hpp"
#include "algorithm/segment_tree.hpp"
#include "algorithm/segment_tree_lazy.hpp"
#include "algorithm/sieve.hpp"
#include "algorithm/spfa.hpp"
#include "algorithm/tarjan.hpp"
