#pragma once

#include <cstdint>

namespace Rain::Networking::Tls {
	enum class AlertDescription : std::uint8_t {
		CLOSE_NOTIFY = 0,
		UNEXPECTED_MESSAGE = 10,
		BAD_RECORD_MAC = 20,
		DECRYPTION_FAILED_RESERVED,
		RECORD_OVERFLOW,
		DECOMPRESSION_FAILURE = 30,
		HANDSHAKE_FAILURE = 40,
		NO_CERTIFICATE_RESERVED,
		BAD_CERTIFICATE,
		UNSUPPORTED_CERTIFICATE,
		CERTIFICATE_REVOKED,
		CERTIFICATE_EXPIRED,
		CERTIFICATE_UNKNOWN,
		ILLEGAL_PARAMETER,
		UNKNOWN_CA,
		ACCESS_DENIED,
		DECODE_ERROR,
		DECRYPT_ERROR,
		EXPORT_RESTRICTION_RESERVED = 60,
		PROTOCOL_VERSION = 70,
		INSUFFICIENT_SECURITY = 71,
		INTERNAL_ERROR = 80,
		USER_CANCELLED = 90,
		NO_RENEGOTIATION = 100,
		UNSUPPORTED_EXTENSION = 110
	};
}
